# Generated by Django 5.2.5 on 2025-08-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Course',
        ),
    ]
