# Generated by Django 5.2.5 on 2025-08-24 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0003_alter_course_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('ethnic', models.CharField(blank=True, max_length=20)),
                ('religion', models.CharField(blank=True, max_length=30)),
                ('hometown', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('title_detail', models.CharField(max_length=100)),
                ('title_granted_at', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('work_position', models.CharField(max_length=100)),
                ('workplace', models.CharField(max_length=100)),
                ('quota_code', models.CharField(blank=True, max_length=200)),
                ('salary_coefficient', models.FloatField(blank=True, null=True)),
                ('salary_coefficient_granted_at', models.DateField(blank=True, null=True)),
                ('recruited_at', models.DateField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('exp_academic', models.JSONField(blank=True, null=True)),
                ('exp_language', models.TextField(blank=True, null=True)),
                ('exp_computer', models.TextField(blank=True, null=True)),
                ('exp_work', models.JSONField(blank=True, null=True)),
                ('researches', models.JSONField(blank=True, null=True)),
                ('published_works', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(db_default='Chưa được duyệt', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('courses', models.ManyToManyField(to='lecturers.course')),
                ('recommender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecturers.lecturer')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
